import { ArrowUpRight, BookOpen, CircleAlert, FileCode2, GitBranch, LoaderCircle } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { ModeSelector } from '../components/mode-selector'
import { ProjectPicker } from '../components/project-picker'
import { demoProjects } from '../domain/demo-data'
import { loadGitHubContext } from '../domain/github-api'
import type { GitHubContext } from '../domain/types'
import { useApp } from '../app'

function ProjectLens({ context }: { context: GitHubContext }) { const readme = context.readme.split('\n').map(line => line.trim()).find(line => line && !line.startsWith('#')) || context.readme.replace(/^#\s+/m, '').trim() || 'README 暂无内容'; return <section className="github-lens"><div className="lens-heading"><div><p className="eyebrow">GITHUB CONTEXT</p><h2>Project Lens</h2></div><span className="lens-branch">{context.defaultBranch}</span></div><article><b>代码事实</b><p><FileCode2 size={14} /> {context.files.length} 个文件已读取</p><div className="file-list">{context.files.slice(0, 5).map(file => <span key={file}>{file}</span>)}</div></article><article><b>项目说明</b><p><BookOpen size={14} /> {readme}</p></article><article><b>开放 Issue</b>{context.issues.length ? context.issues.slice(0, 5).map(issue => <p className="issue-line" key={issue.number}>#{issue.number} {issue.title}</p>) : <p>暂无开放 Issue</p>}</article><p className="lens-note">以上内容是 GitHub 事实；模型推断和用户决定将在进入工作模式后单独标记。</p></section> }
function GitHubConnector({ onLoaded }: { onLoaded: (context: GitHubContext) => void }) { const [repository, setRepository] = useState(''); const [status, setStatus] = useState<'idle' | 'loading' | 'error'>('idle'); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); setStatus('loading'); setError(''); try { onLoaded(await loadGitHubContext(repository.trim())) } catch (cause) { setStatus('error'); setError(cause instanceof Error ? cause.message : 'GitHub 连接失败') } }; return <form className="github-connector" onSubmit={submit}><div className="connector-heading"><GitBranch size={20} /><div><strong>连接 GitHub 仓库</strong><span>读取 README、文件树和开放 Issue，先建立项目上下文。</span></div></div><label htmlFor="github-repository">GitHub 仓库</label><div className="connector-row"><input id="github-repository" value={repository} onChange={event => setRepository(event.target.value)} placeholder="owner/name" autoComplete="off" /><button className="button primary" type="submit" disabled={status === 'loading' || !repository.trim()}>{status === 'loading' ? <><LoaderCircle size={16} className="spin" />连接中</> : '连接仓库'}</button></div>{status === 'error' && <p className="connector-error" role="alert"><CircleAlert size={15} />{error}</p>}<small>公开仓库无需 Token；私有仓库凭证只在服务端使用。</small></form> }
export function HomePage() { const { state, dispatch } = useApp(); const selected = demoProjects.find(item => item.id === state.projectId) ?? (state.githubContext ? { id: state.githubContext.repository, name: state.githubContext.repository, description: state.githubContext.description ?? 'GitHub 项目', language: state.githubContext.defaultBranch } : undefined); return <main className="home-page"><section className="intro"><p className="eyebrow">PROJECT-AWARE CODING AGENT</p><h1>{selected ? '今天要怎么工作？' : '选择一个项目'}</h1><p>{selected ? `已连接 ${selected.name}。选择一种工作方式，所有执行都将以明确的任务合同为起点。` : 'Forge Agent 会先建立项目上下文，再把你的意图变成可审阅、可验证的交付。'}</p></section>{selected ? <><ModeSelector onSelect={mode => dispatch({ type: 'modeSelected', mode })} />{state.githubContext && <ProjectLens context={state.githubContext} />}<button className="back-link" onClick={() => dispatch({ type: 'projectSelected', projectId: '' })}>← 更换项目</button></> : <><GitHubConnector onLoaded={context => dispatch({ type: 'githubContextLoaded', context })} /><ProjectPicker projects={demoProjects} onSelect={projectId => dispatch({ type: 'projectSelected', projectId })} /></>}<aside className="principle-strip"><span>01 先理解项目</span><span>02 明确责任边界</span><span>03 用证据交付</span><ArrowUpRight size={18} /></aside></main> }
